/*BOARDS*/
export const CREATE_BOARDS = 'CREATE_BOARDS';
export const PLACE_SHIPS = 'PLACE_SHIPS';
export const SET_BOARDS = 'SET_BOARDS';

/*GAME*/
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';
export const UPDATE_GAMELIST = 'UPDATE_GAMELIST';
export const START_NEW_GAME = 'START_NEW_GAME';
export const SET_GAME_FINAL = 'SET_GAME_FINAL';
export const SET_CELL_SHOOTED = 'SET_CELL_SHOOTED';

/*PLAYER*/
export const SET_MOVE = 'SET_MOVE';
export const SET_CREDENTIALS = 'SET_CREDENTIALS';
export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const SET_JOINED = 'SET_JOINED';
export const DISCONNECT_OPPONENT = 'DISCONNECT_OPPONENT';

